platform/sun50i/include/platform/irq.h

The RTC block interrupts appear to start at offset 64 from the GIC
interrupts. The order in the GIC table matches with all known R_INTC
interrupts: e.g. MSGBOX at 81 - 64 = offset 17 in the R_INTC.
This omits the R_RSB interrupt, as it is not present on the H5.

plat: sun50i: Add remaining IRQs from the documentation

---

common/work.c

Allows us to execute work in the order that it is added to the queue.
Signed-off-by: Christopher Wong <cwong164@gmail.com>

common: Use circular buffer for work queue

---

common/delay.c
include/delay.h

This is useful for hardware where we can't change registers too fast.
For example, both the CCU and R_TIMER devices require delays in between
two register updates. In these cases, the delay required is much too
short for the overhead of a timer interrupt to be worth using the timer
framework.
Both #75 and #63 have been rebased on top of this PR.

common: Implement a delay function using the wallclock

---

include/string.h
lib/string.c

This library function is needed for the SCPI code to copy messages around.
This is a naive implementation, as performance isn't as important at the moment as code size.

lib: string: Implement memcpy

---

lib/runtime.S

This modifies the existing __udivsi3 function to also return the
remainder (which it was already calculating) in r12. The new wrapper
just copies r12 to the normal return value register (r11).
Signed-off-by: Samuel Holland <samuel@sholland.org>

lib: Implement modulus (__umodsi3)

---

include/lib/util.h
lib/runtime.S

This will be useful for implementing `bitmap_weight()` (counting the number of bits set in a bitmap), which is needed for CPU cluster support.

Implement and expose the popcount builtin

---

drivers/irqchip/irqchip.c
include/drivers/irqchip.h

This brings the irqchip device class in line with improvements
previously made to the clock and wallclock classes. The header
assertions catch devices missing initialization of their irqdev member.
The irqchip.c changes simplify the file, removing a large string for a
case that cannot happen unless irqchip_irq() is called somewhere other
than an IRQ handler.

drivers: irqchip: Add assertions to the irqchip framework

---

drivers/msgbox/sunxi-msgbox.c
include/drivers/msgbox.h
include/drivers/msgbox/sunxi-msgbox.h

This was one of the first drivers I wrote, and I wrote a Linux driver for the same hardware afterward. Update this driver to match current practices (e.g. `0` → `SUCCESS`) and match the Linux driver more closely. Finally, add a new feature to the msgbox class that's needed for SCPI support.

Message box updates

---

common/scpi.c
common/work.c
include/common/interrupts.h
include/lib/compiler.h

Fix synchronization issues with the work queue and SCPI buffer list. These aren't easily visible until we start processing requests at high speed and they suddenly stop working.
Any better names for the header or helper functions? They aren't _really_ locks, as they just prevent preemption by interrupts; but since we're single-threaded, it's effectively the same.

Correctly synchronize shared data structures

---

platform/sun50i/devices.c

Doxygen after-declaration comments still require two asterisks.
Documentation fix
No code changes

platform: sun50i: Fix comment formatting in device list

---

common/scpi.c
include/common/scpi_protocol.h

Because they must match the SCPI ABI (the layout in memory), these
structs were marked as __packed to prevent GCC from inserting padding.
Unfortunately, that also causes GCC to consider them to have an
alignment of 1. Thus, when `struct scpi_mem` is put in `struct
scpi_buffer` along with two other bytes of data, there is no padding
added to the end of the structure. (There should be two bytes of padding
added, to match the correct alignment of 4). This then causes elements
of the `scpi_buffers` array to be misaligned, causing alignment faults.
Fix this by removing the __packed attribute, as the structures are
already laid out in a way that avoids padding between members. Then the
structures have the proper alignment, and padding is added at the end of
`struct scpi_buffer`.
Bug fix
Closes …

SCPI: Fix buffer struct alignment issues

---

Makefile

Tell GCC to produce an error if a variable-length array is used. They're
slow and insecure, and there's no need for them here.
This enhancement is prompted by VLA-removal changes going on in Linux at the moment.
No VLAs are currently in use, nor was using them planned. This just makes that explicit.

Makefile: Prevent accidentally introducing VLAs

---

common/scpi_cmds.c
common/system_power.c
include/common/system_power.h

Implements the SCPI command for shutting down or resetting the system. This allows PSCI to delegate to us, instead of reimplementing the functionality.
Closes #46 
None

Implement SCPI_CMD_SET_SYS_PWR

---

common/css.c
common/scpi_cmds.c
include/common/css.h

This is the generic part of the CSS (core subsystem) code, and the respective SCPI integration. The actual platform-specific driver code is in a separate PR.
Closes #45.
- I haven't added much documentation, but please sanity-check the structure of what I'm doing here. Does anything jump out as weird? I think I figured out the filenames once I realized CSS was the appropriate name here.
- ~~What do you think about using weak functions to provide a default implementation, but allow platforms to provide their own?~~
- ~~What about using functions to provide the number of clusters/cores? Theoretically it could be different between cores on some SoC, but it's not right now. Should I require platforms to supply macros instead? It shouldn't matter from a performance standpoint, because LTO …

CSS (Core Subsystem) API and generic implementation

---

include/lib/math.h
include/lib/util.h
lib/runtime.S

Signed division is needed for regulators (calculating register values from voltage and vice versa).
This blocks #114. This ideally should be merged before either #119 or #120.
This has been tested with lots of different values.

Math library code (small header fix, signed division)

---

drivers/clock/clock.c

Reuse the driver ops pointer for calling driver functions where
appropriate. This saves ~56 bytes.
No functional changes.

drivers: clock: Shrink the generic clock functions

---

platform/sun50i/css.c

This is the platform-specific part of the CSS API. This is the actual core/cluster control code.
Closes #36, Closes #37, Closes #54, Closes crust-firmware/arm-trusted-firmware#4.
This is marked WIP only because I want to refactor a couple of the "wait for xyz" helper functions. The code should work properly as-is.
This requires the `scpi` branch of ATF to actually do anything.
Please test on real hardware: `printf mem > /sys/power/state` should give you back a prompt, not hang. (This is provided by the "standby test code" commit, which shouldn't actually be merged.)

sun50i platform CSS implementation

---

drivers/regulator/axp803.c
drivers/regulator/regulator.c
drivers/regulator/sy8106a.c
platform/sun50i/devices.c

Fixes possible failure to boot on devices with the AXP803 voltage regulator.
Bugfix.

Fix regulator driver issues

---

common/dm.c
drivers/gpio/sunxi-gpio.c
drivers/i2c/sun6i-a31-i2c.c
drivers/msgbox/sunxi-msgbox.c
drivers/timer/sun8i-r_timer.c
drivers/watchdog/sunxi-twd.c
include/common/dm.h
platform/sun50i/devices.c

Move clock setup into a helper function that can handle multiple clocks per device. (The driver has to know how many clocks are needed.)
Needed for #53 
I adjusted the neighboring GPIO function so they match.

Allow multiple clocks per device

---

common/scpi_cmds.c

Since the received payload size is already checked by scpi_handle_cmd,
and there are no variable-size AP-to-SCP payloads, handler functions can
always assume the received payload size. Thus, the parameter is
redundant.
None

common: scpi: Remove rx_size parameter from handlers

---

test/scripts/core_enable_disable.sh

The purpose of this pull request is to add a test to verify that Crust successfully enables/disables CPU cores.
Closes #21 
None

test: Add script to verify Crust enables/disables cores

---

common/scpi_cmds.c
drivers/sensor/sun8i-thermal.c
include/drivers/sensor.h

Implement SCPI sensor reading, so the THS can show up in Linux. Also implement PSU reading/writing.
Closes #49, Closes #48.
A related bugfix is included.

SCPI Sensors/Regulators support

---

drivers/regulator/axp803.c

regulator_set_defaults uses the subdevice count to determine how many
regulators to initialize (which is equal to the number of entries in the
array of default voltages). Make sure this is initialized before calling
the function; otherwise, only the first regulator has its voltage set.

drivers: regulator: axp803: Fix setting default values

---

Makefile
common/scpi_cmds.c

The first patch adds the missing `static` keyword for SCPI command handlers. This makes it easier to omit commands temporarily to make the firmware smaller for debugging. The second patch allows the firmware to build with a wider range of toolchains (see the commit log). 
Neither patch affects the contents of the final firmware binary.

Two small enhancements

---

Makefile
common/debug.c
include/lib/macros.S

- Fixes an alignment issue exposed by gcc9.
- Updates CFLAGS for gcc9.
- Silences a new warning in gcc9.
Only change in the final binary on gcc5 is the order of symbols in `.data`, since the alignment of `console_base` changes from 1 to 4.

GCC 9 compatibility

---

common/scpi_cmds.c

This commit marks the branch point for the "legacy" proof-of-concept
Crust 0.1 that tries to implement and expose as much of the SCPI
specification as possible. This version of Crust follows an ABI (load
address, SCPI shared memory address, and mailbox channel assignment)
that is different from what will hopefully be merged into mainline Linux
and ATF.

scpi: Bump the firmware version to 0.1

---

drivers/msgbox/Makefile
drivers/msgbox/msgbox.c
drivers/msgbox/msgbox.h
drivers/msgbox/sunxi-msgbox.c
include/drivers/msgbox.h
include/drivers/msgbox/sunxi-msgbox.h

This is a partial fix for issue: #171
"Remove static inline wrappers from driver headers"
Signed-off-by: Vincent Legoll <vincent.legoll@gmail.com>

Move msgbox_driver{,_ops} to a private header

---

configs/pinetab_defconfig

This PR adds a defconfig for the PineTab, based on the PineBook config.

configs: add PineTab defconfig

---

Makefile

Allow BUILDCC to be overridden, as crust build fails when cc is missing (e.g. minimal Ubuntu 20.04)
Issue identified in LibreELEC builds with the minimal focal 20.04 docker. `cc` is not available. Patch currently in place - https://github.com/LibreELEC/LibreELEC.tv/pull/5953 - but better solution is to allow `BUILDCC` to be overridden and use the toolchain compiler (not the Operating System supplied `cc` compiler.)
Error log
```
BUILD      crust (target)
TOOLCHAIN      manual
...
HOSTCC  build/3rdparty/kconfig/conf.o
/bin/sh: 1: exec: cc: not found
make[1]: *** [Makefile:170: build/3rdparty/kconfig/conf.o] Error 127
...
```

Makefile: allow override of BUILDCC
